services:
  postgres_db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/new_postgresql/data
  nasa-api:
    build: .
    depends_on:
      - postgres_db
    ports:
      - 8080:8080
volumes:
  postgres_data:
    driver: local
